import streamlit as st
from news_fetcher import fetch_news
from sentiment_analyzer import analyze_sentiment
from report_generator import generate_report, save_report

st.set_page_config(
    page_title="MarketInsight AI",
    page_icon="📊",
    layout="wide"
)

st.title("📊 MarketInsight — Agentic AI Market Intelligence")
st.markdown("**Autonomous AI agents analyze market news and generate professional investment reports!**")
st.markdown("---")

col1, col2 = st.columns(2)

with col1:
    company_name = st.text_input(
        "Enter Company Name",
        value="Infosys",
        help="Example: Infosys, TCS, Tesla, Apple"
    )

with col2:
    st.markdown("###")
    analyze_button = st.button("🔍 Analyze Company", type="primary")

if analyze_button:
    import os
    from dotenv import load_dotenv
    load_dotenv()

    st.markdown("---")

    col3, col4, col5 = st.columns(3)
    with col3:
        st.info("🤖 Agent 1: News Fetcher")
    with col4:
        st.info("🧠 Agent 2: Sentiment Analyzer")
    with col5:
        st.info("📝 Agent 3: Report Generator")

    st.markdown("---")

    with st.spinner("Agent 1 fetching latest news..."):
        import importlib
        import config
        config.COMPANY_NAME = company_name
        headlines = fetch_news()

    st.success(f"✅ Agent 1 Complete — Found {len(headlines)} headlines!")

    st.subheader("📰 Latest News Headlines")
    for i, headline in enumerate(headlines, 1):
        st.write(f"**{i}.** {headline}")

    st.markdown("---")

    with st.spinner("Agent 2 analyzing sentiment..."):
        sentiment = analyze_sentiment(headlines)

    st.success("✅ Agent 2 Complete — Sentiment analyzed!")

    st.subheader("📈 Sentiment Analysis")
    st.write(sentiment)

    st.markdown("---")

    with st.spinner("Agent 3 generating report..."):
        report = generate_report(headlines, sentiment)
        filename = save_report(report)

    st.success("✅ Agent 3 Complete — Report generated!")

    st.subheader("📋 Market Intelligence Report")
    st.write(report)

    st.markdown("---")
    st.download_button(
        label="📥 Download Full Report",
        data=report,
        file_name=filename,
        mime="text/plain"
    )

    st.success("🎉 Analysis Complete!")
    st.info("💡 This report is generated by 3 autonomous AI agents working together!")